### ISSUE TITLE
Enable send e-mail functionality for CVS2-dev

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#193]
**Original report on BitBucket by sigit nugraha.**

----------------------------------------

In the CVS2-dev, it seems the current existing users need to reset their password before they are able to log-in. There is already a reset-password feature that uses e-mail.

The e-mail server configuration on the app is located in application-prod.yml

```
spring:
  mail:
    host: localhost
    port: 25
    username:
    password:
```

About the CESSDA sender e-mail address from CESSDA to reset the password, probably [*email address removed*](mailto:*email address removed*), or most likely CESSDA already has official e-mail address for this.

‌

‌
