### ISSUE TITLE
Trial the use of ChatGPT to review code modifications

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cvs.two#722]
ChatGPT can be used to comment on the content of Pull Request.

The purpose of this trial is to: determine if the ChatFPT comments add any value to the code review process; assess the likely cost of using the ChatGPT API for this purpose, once the free trial period expires.

Steps to configure ChatGPT code reviews:

- [ ] Create a ChatGPT API account (https://platform.openai.com/signup/)
- [ ] Create an API key and copy it
- [ ] In GitHub, create a Repository secret called 'OPEN_API_KEY' and paste the API key into it
- [ ] Modify the Actions permissions (see attachments) to 'Allow all actions and reusable workflows' and to have workflow permissions to 'read and write' and 'create and approve pull requests'
- [ ] Add chatgpt-review.yaml to the .github/workflows folder of the repo (see code below)

**Comment by john-shepherdson** [comment]
![Repo Action permission 1](https://github.com/cessda/cessda.cvs.two/assets/107628491/c2d05c4d-305a-465c-985e-502d436e0705)

![Repo Action permission 2](https://github.com/cessda/cessda.cvs.two/assets/107628491/de041b93-892c-4955-96ea-1cc034500a9f)

**Comment by john-shepherdson** [comment]
```
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - name: ChatGTP explain code
        uses: cirolini/chatgpt-github-actions@v1.3
        with:
          openai_api_key: ${{ secrets.OPEN_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "text-davinci-002" #optional
          openai_temperature: 0.5 #optional
          openai_max_tokens: 2048 #optional
          mode: files # files or patch 
```
